@host = http://localhost:5000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OWU0YzVhMS0zZjViLTQ0MjktODFmNC1kMDc2ZGQ1NzEwODMiLCJqdGkiOiIwOTlkMjc4ODBhOGE0NDk0ODRmYjI1M2JiYjQ0YTg5OCIsInVuaXF1ZV9uYW1lIjoiODllNGM1YTEtM2Y1Yi00NDI5LTgxZjQtZDA3NmRkNTcxMDgzIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsIm5iZiI6MTc4MDkxMjExMCwiZXhwIjoxNzgwOTE1NzEwLCJpc3MiOiJzdHJlYWtseSIsImF1ZCI6InN0cmVha2x5LWFwaSJ9.Pe8rKg7VleF0DJfiX-faeWRXiode_TH0DNcbmStP0KU

### Sign up
POST {{host}}/Auth/sign-up
Content-Type: application/json

{
  "email": "test@example.com",
  "userName": "tester",
  "password": "secret123",
  "fullName": "Test User"
}

### Sing in
POST {{host}}/Auth/sign-in
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "secret123"
}

### Logout
POST {{host}}/Auth/logout
Authorization: Bearer {{accessToken}}


### Sign up with real email confirmation
POST {{host}}/Auth/sign-up
Content-Type: application/json

{
  "email": "gargas.w@gmail.com",
  "userName": "Wojtek",
  "password": "secret123",
  "fullName": "Wojciech Gargas"
}

### Sing in as Wojtek
POST {{host}}/Auth/sign-in
Content-Type: application/json

{
  "email": "gargas.w@gmail.com",
  "password": "secret123"
}
